name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.0'
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          npm i
          zip -r Flow.Launcher.Plugin.Translate.zip . -x '*.git*'
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'Flow.Launcher.Plugin.Translate.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}